version: 2.1
workflows:
    lint_and_publish:
        jobs:
            - lint
            - publish:
                  context: cloudflare
                  filters:
                      branches:
                          only:
                              - main

# Just for reusing below
step_defs:
    - run: &node_version
          name: Set Node version
          command: |
              nvm install v16
              nvm alias default v16
              echo "nvm use default" >> $BASH_ENV
    - run: &check_version
          name: Check Node version
          command: node -v | grep v16

jobs:
    lint:
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: |
                      yarn build
            - run:
                  name: Check lint
                  command: |
                      yarn lint:check
    publish:
        machine:
            image: ubuntu-2204:2022.04.1
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run: *node_version
            - run: *check_version
            - run:
                  name: Install Packages
                  command: yarn
            - run:
                  name: Build
                  command: |
                      yarn build
            - run:
                  name: Publish
                  command: |
                      npx wrangler@2.1 publish
